FROM node:18-alpine

WORKDIR /app

# Garante que o Docker veja o package.json
COPY backend/api-gateway/package.json ./

# Instala apenas as dependências de produção
RUN npm install --only=production

# Agora copia o restante dos arquivos
COPY backend/api-gateway/ .

EXPOSE 8081
CMD ["npm", "start"]
