services:
  db:
    image: postgres:15
    container_name: marketbot-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketbot_dev
    ports:
      - "5033:5433"    # <— aqui, hostPort:containerPort
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
