FROM node:18-alpine

WORKDIR /app

# Copiar toda a estrutura backend preservando hierarquia
COPY backend/ ./backend/

# Ir para o diretório api-gateway
WORKDIR /app/backend/api-gateway

# Instalar dependências
RUN npm install --only=production

EXPOSE 8081
CMD ["npm", "start"]
