[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildCommand = "npm ci --omit=dev && echo FORCE_BUILD_$(date +%s)"

[deploy]
startCommand = "echo RAILWAY_FORCE_START && node main.js"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
FORCE_DEPLOY = "RAILWAY_BYPASS_CACHE"
CACHE_BUSTER = "FORCE_
1754515134,9465
"
DATABASE_URL = "postgresql://postgres:ELjbkkgUASRCtdTAXVFgIssOXiLsRCPq@trolley.proxy.rlwy.net:44790/railway"
