#!/bin/bash
# 🚀 SCRIPT DE VERIFICAÇÃO DO DEPLOY RAILWAY
# Verifica se o deploy está sendo executado com os novos arquivos

echo "🚀 VERIFICANDO DEPLOY DO SISTEMA INTEGRADO V3..."
echo "=================================================="
echo ""

echo "📋 ARQUIVOS PRINCIPAIS ENVIADOS:"
echo "✅ servidor-integrado-completo.js - Servidor HTTP + WebSocket"
echo "✅ sistema-orquestrador-completo.js - Orquestração de trading"
echo "✅ dashboard-live-data.js - WebSocket tempo real"
echo "✅ controlador-sistema-web.js - APIs REST"
echo "✅ package-clean.json - Dependências atualizadas"
echo "✅ Dockerfile.fixed - Container otimizado"
echo ""

echo "🔧 CONFIGURAÇÕES DO RAILWAY:"
echo "📦 Package: package-clean.json → package.json"
echo "🐳 Dockerfile: Dockerfile.fixed"
echo "🚀 Start Command: node servidor-integrado-completo.js"
echo "🌐 Port: 3000"
echo "📡 WebSocket: /ws/dashboard"
echo ""

echo "✨ FUNCIONALIDADES ATIVAS:"
echo "🎛️ Sistema Liga/Desliga Completo"
echo "📊 Leitura de Mercado (Fear & Greed + BTC Dominance)"
echo "🤖 IA Guardian para Análise de Sinais"
echo "👥 Sistema Multiusuário com Comissionamento"
echo "📡 Processamento de Webhooks TradingView"
echo "👁️ Monitoramento em Tempo Real"
echo "💰 Fluxo Completo: Sinal → Operação → Comissão"
echo "📱 Dashboard Live - Dados minuto a minuto via WebSocket"
echo ""

echo "📡 ENDPOINTS PRINCIPAIS:"
echo "🟢 POST /api/system/start - Ligar sistema"
echo "🔴 POST /api/system/stop - Desligar sistema"
echo "📊 GET  /api/system/status - Status do sistema"
echo "📡 POST /api/webhook/tradingview - Webhook TradingView"
echo "🎛️ GET  /api/dashboard - Dashboard completo"
echo "📱 GET  /api/dashboard/connections - Conexões WebSocket"
echo "📢 POST /api/dashboard/broadcast - Enviar mensagem"
echo "❤️ GET  /health - Health check"
echo "🎛️ GET  /control - Painel de controle"
echo "📡 WS   /ws/dashboard - WebSocket tempo real"
echo ""

echo "🎯 APÓS O DEPLOY:"
echo "1. Acessar: https://coinbitclub-market-bot-production.up.railway.app/"
echo "2. Verificar health: https://coinbitclub-market-bot-production.up.railway.app/health"
echo "3. Painel controle: https://coinbitclub-market-bot-production.up.railway.app/control"
echo "4. Ligar sistema: Clicar em '🟢 Ligar Sistema'"
echo "5. WebSocket: wss://coinbitclub-market-bot-production.up.railway.app/ws/dashboard"
echo ""

echo "💡 MONITORAMENTO:"
echo "📊 Logs Railway para acompanhar inicialização"
echo "❤️ Health checks a cada 30 segundos"
echo "📡 WebSocket heartbeat a cada 30 segundos"
echo "🔄 Auto-restart em caso de falha"
echo ""

echo "🎉 PUSH COMPLETO REALIZADO COM SUCESSO!"
echo "⏳ Aguardando deploy automático do Railway..."
echo "=================================================="
